# Java Gradle CircleCI 2.0 configuration file
# See: https://circleci.com/docs/2.0/language-java/
version: 2

workflows:
  version: 2
  build_and_publish:
    jobs:
      - build
      - test
      - package:
          requires:
            - build
      - deploy:
          requires:
            - package

jobs:
  build:
    docker:
      - image: openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew bootJar
      - persist_to_workspace:
          root: ./
          paths:
            - build/
            - .gradle/  
  test:
    docker:
      - image: openjdk:8-jdk
    steps:
      - checkout
      - run: ./gradlew test
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests/test/index.html
      - store_artifacts:
          path: build/jacoco/tests/html/index.html

  package:
    docker:
      - image: docker:dind
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - checkout
      - attach_workspace:
          at: ./
      - run: docker build --iidfile imageid.txt  -t registry.heroku.com/$HEROKU_APP_NAME/inventory-app:$CIRCLE_SHA1 .
      - run: docker login -u _ -p $HEROKU_TOKEN registry.heroku.com
      - run: docker push registry.heroku.com/$HEROKU_APP_NAME/inventory-app:$CIRCLE_SHA1
      - persist_to_workspace:
          root: ./
          paths:
            - imageid.txt
  deploy:
    docker:
      - image: docker:dind
    steps:
      - setup_remote_docker:
          version: 19.03.13
      - attach_workspace:
          at: ./
      - run: apk add --no-cache curl
      - run:
          name: "Deploying..."
          command: |
            curl -X PATCH https://api.heroku.com/apps/$HEROKU_APP_NAME/formation --header "Content-Type: application/json" --header "Accept: application/vnd.heroku+json; version=3.docker-releases" --header "Authorization: Bearer ${HEROKU_TOKEN}" --data '{ "updates": [ { "type": "web", "docker_image": "'$(cat imageid.txt)'" } ] }'
